# Generated by Django 3.1.2 on 2020-11-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.TextField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('precio', models.TextField(max_length=10)),
                ('stock', models.TextField(max_length=5)),
                ('marca', models.TextField(max_length=20)),
                ('codigo', models.TextField(max_length=100)),
            ],
        ),
    ]
