# Generated by Django 3.1.2 on 2020-11-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.TextField(max_length=10)),
                ('codProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('correo', models.TextField(max_length=100)),
                ('telefono', models.TextField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.AddField(
            model_name='carro',
            name='rutCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.cliente'),
        ),
    ]
